name: Validate
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11
      - name: Install arch-as-code
        run: |
          mkdir -p ~/arch-as-code && curl -s https://api.github.com/repos/trilogy-group/arch-as-code/releases/latest |  grep "browser_download_url" | cut -d : -f 2,3 | tr -d \" | xargs curl -L | tar zx --strip-components 1 -C ~/arch-as-code ~/arch-as-code/bin/arch-as-code -V
      - name: Validate
        run: ~/arch-as-code/bin/arch-as-code validate .
